### DISCUSSION TITLE
로그 모니터링 구축

### DISCUSSION THREAD

**Discussion by jminkkk** [woowacourse-teams/2024-code-zap#349] [기록해봐요]
로그 모니터링 구축

로키, 프롬테일, 그라파나 사용

**Comment by kyum-q** [comment]
# 설정 파일 분석

**Reply by kyum-q** [reply]
## loki-config.yml

```yml
auth_enabled: false # 인증 안하고, 접근 가능하도록

server:
  http_listen_port: 3100 # 어떤 port로 열려있는지

common: 
  instance_addr: 127.0.0.1 # loki에 접속 가능한 ip
  path_prefix: /tmp/loki # 디렉토리가 기본 경로
  storage: # 데이터 저장 설정
    filesystem:
      chunks_directory: /tmp/loki/chunks  # 청크 파일 디렉터리
      rules_directory: /tmp/loki/rules # loki 규칙 디렉터리
  replication_factor: 1 # 데이터 복제 수
  ring: # 분산 클러스터
    kvstore: 
      store: inmemory # 영구적이지 않으며, Loki를 재시작하면 데이터가 사라진다

query_range:
  split_queries_by_interval: 24h # 어떤 간격으로 병렬 처리
  results_cache:
    cache:
      embedded_cache: # 내장 캐시 사용
        enabled: true # 캐시 사용 활성화
        max_size_mb: 100 # 캐시의 최대 크기

query_scheduler:
  max_outstanding_requests_per_tenant: 4096 # 동시 처리 가능한 최대 쿼리 요청 수

## 추후 지워도 될 것 같음 
frontend:
  max_outstanding_per_tenant: 4096 # 동시 처리 가능한 최대 요청 수

schema_config: # 데이터가 어떻게 저장될지
  configs:
    - from: 2024-07-31
      store: tsdb 
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h
```

### Common
여러 모듈 간에 공유할 공통 구성입니다. 다른 섹션에서 더 구체적인 구성을 지정한 경우 이 섹션 내의 관련 구성은 무시됩니다.

### query
: Loki에서 저장된 로그 데이터를 검색하거나 조회하는 요청을 의미

> 사용자는 Loki에 쿼리(query)를 보내 특정 로그 데이터를 검색하거나, 일정 기간 동안 발생한 로그를 집계하는 등의 작업을 수행

### tsdb

시계열 데이터를 효율적으로 저장하고 조회할 수 있도록 설계된 데이터베이스

> 시계열 데이터 : 시간에 따라 변화하는 데이터를 의미

**Reply by kyum-q** [reply]
## promtail

```yml
server:  
  http_listen_port: 9080 # 어떤 port로 열려있는지
  grpc_listen_port: 0
  positions:  # 로그 수집 위치 기록 파일 설정
    filename: /tmp/positions.yaml 
  clients: # Loki 서버의 URL을 설정
    - url: http://10.0.0.245:3100/loki/api/v1/push
  scrape_configs:  
    - job_name: spring_logs
      static_configs:  
        - targets:  
          - localhost # 로그를 수집할 대상
            labels: # 수집된 로그에 추가될 메타데이터(라벨)
              job: spring_logs  
              env: dev # 개발 환경
              __path__: /mnt/code-zap/spring-log/**/*.log # 가져올 log 파일 path 
      pipeline_stages: # 로그 처리 단계
        - regex: # 정규 표현식을 사용해 로그의 라벨 추출
            expression: '^\[(?P<level>\w+)\]\[(?P<timestamp>.*?)\]\[(?P<correlationId>.*?)\]\[(?P<logger>.*?)\]\s(?P<message>.*)$'  
        - labels:  # 라벨
            level:  
            correlationId:  
            logger:  
        - timestamp:  
            source: timestamp  
            format: 01-02 15:04:05  
        - output:  
            source: message  

    - job_name: nginx_logs  
      static_configs:  
        - targets:  
            - localhost  
          labels:  
            job: nginx_logs  
            env: dev  
            __path__: /var/log/nginx/code-zap/dev/*.log  
      pipeline_stages: # 로그 처리 단계
        - regex:  
            expression: '^(?P<ip>\S+) \S+ \S+ \[(?P<timestamp>\S+) \S+\] "(?P<method>\S+) (?P<path>\S+) (?P<protocol>\S+)" (?P<status>\d+) (?P<size>\d+) "(?P<referer>.*)" "(?P<useragent>.*)"$'  
        - labels: # 라벨
            method:  
            path:  
            protocol:  
            status:  
        - timestamp:  
            source: timestamp  
            format: 02/Jan/2006:15:04:05 -0700
```

### position 섹션

Promtail은 재시작 후에도 이전에 어디까지 읽었는지 기억할 수 있게 설정
