### ISSUE TITLE
[BUG] 로컬 환경에서 서버 실행 시 예외 발생

### ISSUE THREAD

**Issue by zeus6768** [woowacourse-teams/2024-code-zap#137]
## 🐞 어떤 버그인가요?

- `org.hibernate.tool.schema.spi.CommandAcceptanceException` 발생
- 기능에 문제를 일으키지는 않습니다. 

## 🙄 어떤 상황에서 발생한 버그인가요?

- 로컬 환경에 code-zap 데이터베이스가 존재할 경우 서버를 실행하면 해당 에러 발생

## 🎁 예상 결과

- 예외 발생 x

## ⏳ 예상 소요 시간

- 1시간 이내

### AS-IS

```yml
spring:
  jpa:
    hibernate:
      ddl-auto: create
```

### TO-BE

```yml
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
```
