### ISSUE TITLE
[INFRA] Git Submodule을 사용하여 AWS EC2에 위치한 설정을 관리하도록 변경

### ISSUE THREAD

**Issue by zeus6768** [woowacourse-teams/2024-code-zap#744]
#725 

## 개요
- 현재 코드잽은 EC2에 도커 컴포즈를 구성하여 서버를 구축했습니다. 
- `compose.yml`, `nginx.conf`, `application.yml` 등의 설정 파일이 변경될 때마다 서버에 접속해야 합니다. 

### 요구사항
- 변경 내역을 추적할 필요가 있습니다.
- 우테코 캠퍼스 네트워크를 벗어나도 작업할 수 있어야 합니다. 
- 프로젝트와 프로젝트 설정 파일을 하나의 IDE에서 관리해서 생산성을 높일 수 있습니다. 

### 체크리스트
- [x] private 저장소 collaborators 추가
- [x] 각 설정 파일이 올바른지 확인
  - [x] `compose.yml`
  - [x] `spring/application.yml`
  - [x] `promtail/promtail-config.yml`
  - [x] `nginx/nginx.conf`
- [x] 다음의 파일들이 `backend_cd.yml` workflow의 `Compose 환경변수 주입` 작업으로 생성된 .env 파일을 올바르게 참조하는지 확인
  - [x] `spring/application.yml`
  - [x] `promtail/promtail-config.yml`
- [x] 프로젝트 저장소의 Secret과 private 저장소의 secret이 일치하는지 확인
  - [x] Develop Environments Secret → private/develop/secret
  - [x] Production Environments Secret → private/production/secret

**Comment by zeus6768** [comment]
[Git submodule 공식문서](https://git-scm.com/book/ko/v2/Git-%EB%8F%84%EA%B5%AC-%EC%84%9C%EB%B8%8C%EB%AA%A8%EB%93%88)를 참고했습니다.

**Comment by zeus6768** [comment]
# Private Repo 생성

<img width="640" alt="스크린샷 2024-10-06 오후 2 26 19" src="https://github.com/user-attachments/assets/008e5bbd-752d-4296-af17-6481cb0c2ed4">

- codezap2024@gmail.com 계정으로 생성한 Github 저장소입니다.
- 공개 저장소에 저장할 경우 보안 문제가 생길 수 있는 데이터를 저장합니다.
- `TODO`: Read & Write 권한을 위해 Collaborator 초대를 해야 합니다.

**Comment by zeus6768** [comment]
## 작업 방식 변경

### 3.1 Secret을 변경하는 경우

1. Public 저장소에서 이슈 발행 (원래 하던거)
2. Private 저장소의 `develop` 또는 `production` 브랜치에서 `secret` 파일 수정 및 Push
3. Public 저장소의 Settings에서 secret 변경
4. Public 저장소에서 Pull Request (원래 하던거)

### 3.2 서버 구성을 변경하는 경우

1. Public 저장소에서 이슈 발행 (원래 하던거)
2. Private 저장소의 main 브랜치에서 작업 후 push
3. Public 저장소에서 Pull Request (원래 하던거)

### 3.3 팁

Private 저장소에 push 되는 작업마다 PR을 작성할 필요 없어요. 

인프라 작업을 위해 private 저장소에 여러 번의 push를 해도 돼요.

Public 저장소 입장에서는 private 저장소에서 몇 번의 변경이 일어났든, 서브모듈 디렉토리의 해시값만 변경된 것으로 추적돼요.

**Comment by zeus6768** [comment]
# 4. Spring yml 파일 위치 변경

스프링 yml 파일들을 모두 `main/resource` 디렉토리로 이동했어요. 

## AS-IS

![스크린샷 2024-10-17 오후 2 02 22](https://github.com/user-attachments/assets/ab26d9b5-ae92-4328-9f6e-14a811c154ff)

## TO-BE

![스크린샷 2024-10-17 오후 2 04 06](https://github.com/user-attachments/assets/2b35269b-3dca-4e4a-acad-f69475d83d01)

변경 후에 아주 좋아지는 점이 두 개 있어요.  

1. SSH 접속으로 서버마다 yml 파일을 수정할 필요가 없어요. 
2. `java -jar` 명령어로 서버를 실행할 때 yml 파일 위치를 명시하지 않아도 돼요. 

```yml
# compose.yml

## AS-IS
  spring:
    entrypoint: [
      "java", "-jar",
      "-Dspring.config.location=/app/application-prod.yml,/app/application-db/yml,/app/application-actuator.yml,/app/application-swagger.yml",
      "-Dspring.profiles.active=${SPRING_PROFILE}",
      "/app/code-zap.jar"
    ]

## TO-BE
  spring:
    entrypoint: [
      "java", "-jar",
      "-Dspring.profiles.active=${SPRING_PROFILE}",
      "/app/code-zap.jar"
    ]
```

다음의 [블로그 글](https://colabear754.tistory.com/112)을 참고해서 구성했어요.

**Comment by zeus6768** [comment]
# 5. 환경변수 주입

개발 환경과 운영 환경에서 같은 설정을 사용하고, 환경에 따라 값만 달라지게 구성했어요. 

`application-cors.yml`을 예로 들어볼게요. 

```yml
cors:
  allowed-origins: ${ALLOWED_ORIGINS}
  allowed-origins-patterns: ${ALLOWED_ORIGINS_PATTERNS}
```

여기에 주입되는 `ALLOWED_ORIGINS`와 `ALLOWED_ORIGINS_PATTERNS`는 개발 환경과 운영 환경에서 다를 거에요. 

이런 값들은 private 저장소 각 브랜치의 `ENV_VARIABLES`라는 secret을 통해 주입돼요. 

```yml
# backend_cd.yml
      - name: Compose 환경변수 주입
        working-directory: ${{ secrets.PROJECT_PATH }}
        run: ${{ secrets.ENV_VARIABLES }}
```

각 저장소에 가서 어떤 값이 주입되는지 확인해볼까요?

[Develop Secret | 2024-code-zap-private](https://github.com/codezap2024/2024-code-zap-private/blob/develop/secret)

[Production Secret | 2024-code-zap-private](https://github.com/codezap2024/2024-code-zap-private/blob/production/secret)

다음과 같은 스크립트가 무슨 뜻인지 궁금하죠?
```
cat <<EOF > .env
(변수들)
EOF
```

위 스크립트는 `(변수들)`을 출력해서 `.env` 파일로 저장하는 기능을 해요. 

여러 줄을 한 번에 출력하고 파일로 만들기 위해 저런 명령어를 사용했어요. 

또, `.env` 라는 이름의 파일로 만든 이유가 있어요. 

도커 컴포즈는 명시하지 않아도 `compose.yml`과 같은 폴더 내의 `.env`라는 파일을 참조해요. 

그래서 다음과 같은 설정이 가능한 거에요. 

```yml
# compose.yml
  spring:
    environment:
      TZ: ${TZ}
      SPRING_PROFILE: ${SPRING_PROFILE}
      MYSQL_READER_URL: ${MYSQL_READER_URL}
      MYSQL_WRITER_URL: ${MYSQL_WRITER_URL}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      ALLOWED_ORIGINS_PATTERNS: ${ALLOWED_ORIGINS_PATTERNS}
```

`SPRING_PROFILE`, `MYSQL_READER_URL` 등의 변수가 모두 `.env`에 저장되어있기 때문이죠!
