### ISSUE TITLE
[FEAT] AWS 서버 마이그레이션

### ISSUE THREAD

**Issue by jminkkk** [woowacourse-teams/2024-code-zap#944]
## 📌 어떤 기능인가요?
> 우테코 지원 중단에 따른 서버를 마이그레이션한다.

## 📜 작업 상세 내용
- [x] 운영 환경 DB
- [x] 운영 환경 WAS
- [x] 개발 환경 DB
- [x] 개발 환경 WAS
- [x] 모니터링 서버
- [x] 변경된 서버 구조도 작성

**Comment by jminkkk** [comment]
# SSL 인증서 발급

금전 이슈로 무료인 Cerboot을 사용하여 발급 받는다.

## Cerboot 인증서 발급 방법

손쉬운 발급을 위해 도커를 사용했다.

1. compose 파일
```
  # compose.yml 참고
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/data/conf:/etc/letsencrypt
      - ./certbot/data/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
```

2. 명령어 입력
docker compose run --rm --entrypoint "certbot certonly --manual --preferred-challenges=dns -d code-zap.com" certbot

![image](https://github.com/user-attachments/assets/d40fe669-ca86-4b35-9d82-e6ea5f833d29)

위와 같은 화면이 나오면 3번

3. 호스팅케이알에 TXT 레코드로 다음과 같이 등록 
(monitor가 서브도메인)

<img width="864" alt="image" src="https://github.com/user-attachments/assets/6e7782f9-4a15-4f58-9145-2746c439f617">

4. 발급 시에 생긴 pem 키 nginx 에서 사용 가능하도록 옮기기 

3번까지 했다면 `/certbot/conf/live`에 pem키가 생깁니다.

이 키를 nginx 컨테이너에서 접근가능하도록 옮깁니다.

생성된 pem키에 접근 권한이 없기 때문에 sudo su를 통해 생성된 pem를 복사 해옵시당

<img width="718" alt="image" src="https://github.com/user-attachments/assets/3219e24c-c857-4b5c-b6a2-7ccd71d259af">

fullchain.pem, privkey.pem를 복사하여 nginx 하위에 둡니다.

<img width="213" alt="스크린샷 2024-12-03 오전 12 34 43" src="https://github.com/user-attachments/assets/8bfd17c2-8fa2-47b6-9493-8c0214cfd877">

> 참고: [Let’s encrypt로 만든 인증서 살펴보기](https://keyhyuk-kim.medium.com/lets-encrypt%EB%A1%9C-%EB%A7%8C%EB%93%A0-%EC%9D%B8%EC%A6%9D%EC%84%9C-%EC%82%B4%ED%8E%B4%EB%B3%B4%EA%B8%B0-8b00a29a8bd3)
> cert.pem : yourdomain.com 의 인증서 (public key)
> chain.pem : Let’s encrypt의 Intermediate 인증서.
> fullchain.pem : cert.pem 과 chain.pem을 합친 결과
> privkey.pem : cert.pem publickey에 대응하는 비밀키
