### ISSUE TITLE
[REFACTOR] CD 파이프라인 Verify Deploy Succeed job의 코드를 쉘스크립트로 분리

### ISSUE THREAD

**Issue by zeus6768** [woowacourse-teams/2024-code-zap#97]
## 📌 어떤 기능을 리팩터링 하나요?

#96 

Verify Deploy Succeed 작업을 쉘스크립트로 분리합니다. 

## AS-IS

```yml
- name: Verify Deploy Succeed
  run: |
    sleep 10 # Ensure there is enough time for the application to start
    pgrep -f 'java -jar' || { echo "Deploy Failed" }
```

## TO-BE
```yml
- name: Verify Deploy Succeed
  run: ./verify.sh
```

## ⏳ 예상 소요 시간
4시간
